config/routes.rb
Rails.application.routes.draw do
  
  resources :customer_details do
    collection do 
      get :existing_customer, :search_customer, :status, :update_search, :search_customer_status, :customer_status
      get :existing_customer, :search_customer, :work_done, :pending_status, :good_delivered, :show_work_done
      get :show_pending_status, :show_good_delivered, :report, :show_transactions_list
      post :transactions_list
    end
    member do
       get :customer_receipt, :show_engineer_copy, :inventory_item, :inventory, :without_adding_items, :invoice, :edit_status
      patch :update_status
    end
     resources :inventory_items
  end

   resources :inventory_items do
    collection do 
      get :select_inventory,:select
    end
    member do
      get :add_product_existing_customer, :show_invoice
    end
  end


  resources :engineer_details 

  resources :inventories do
    collection do
      post :import
      get  :load_item_data
      get :search_inventory
      get :view_all
    end
  end

  resources :inventory_types

  root 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :employees
  resources :employee_types
  resources :general_settings
 
  resources :home do
  	collection do
  		get :dashboard
  	end
  end

  resources :inventory_transfers do
    collection do
      get :select
      get :assign_all
      get :remove_all
      get :inventory_transfer
    end
    member do
      get :transfer
    end
  end

  resources :reports do 
    collection do
    get :select, :report, :transfer
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :inventory_type
  belongs_to :transfer, optional:true
  has_many :inventory_items
  scope :shod, ->(id) { where(id: id).take }
  belongs_to :customer_detail, optional:true
  validates :branch, presence:true, :case_sensitive => false
  validates :description, presence:true, :case_sensitive => false
  validates :part_no , presence:true, :case_sensitive => false
  validates :inventory_type_id, presence:true

  def self.search_inventory(search)
    return if search.empty?
    Inventory.where "concat_ws(' ',description,branch)like ? \
    OR concat_ws(' ',branch,description)like ? \
    OR part_no like ?", "#{search}%", "#{search}%", "#{search}%"
  end
  
  def self.to_csv(fields = column_names, options = {})
   CSV.generate(options) do |csv|
    csv << column_names
    all.each do |inventory|
      csv << inventory.attributes.values_at(*column_names)
    end
    end
  end

COLUMNS_TO_STRING = ["inventory_type_id"] # and so on

def self.import(file)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    row = clean_for row, COLUMNS_TO_STRING
    record = Inventory.find_by(:id => row["id"]) || new
    record.attributes = row.to_hash.slice(*row.to_hash.keys)
    record.save!
  end
end

def self.clean_for row_as_hash, string_columns_array
  row_as_hash.each do |key, value|
    if string_columns_array.include?key
      row_as_hash[key] = value.to_i.to_s
    end
  end
end



def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path)
  when ".xls" then Roo::Excel.new(file.path)
  when ".xlsx" then Roo::Excelx.new(file.path)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

app/models/inventory_type.rb
class InventoryType < ApplicationRecord
	scope :shod, ->(id) { where(id: id).take }
	has_many :inventories, dependent: :destroy
	has_many :inventory_logs, dependent: :destroy
	validates :name, presence:true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
    respond_to do |format|
    format.html
    format.json
    format.js 
    format.csv { send_data @inventories.to_csv(['branch','part_no','description','total_stock_qty','total_stock_value','warehouse_stock_qty','engineer_stock_qty','location1',
      'location2','location3','map','status','latest_modify_date','inventory_type_id']) }
    format.xls { send_data @inventories.to_csv(col_sep: "\t") }
    end
  end


  def load_item_data
    @inventory = Inventory.find_by_id(params[:inventory_id]).present? ? Inventory.find(params[:inventory_id]) : Inventory.unscoped.find_by_id(params[:inventory_id])
    render :json => [ @inventory.description || "" , @inventory.branch, @inventory.map || ""]
  end

  def view_all
    @inventories = Inventory.all
  end

    # find Inventory from database which we have type in text box
  def search_inventory
    if params[:search].present?
    @inventories ||= Inventory.search_inventory(params[:search])
    respond_to do |format|
    format.js {render layout: false if request.xhr?}
        # format.js {render :partial => 'search_all' ,:layout => false}
    end
    end
  end


  def import
    Inventory.import(params[:file])
    redirect_to inventories_path, notice: "Inventories imported successfully."
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    transfered_stock_qty = params[:inventory][:total_stock_qty]
    @inventory.update(:transfered_stock_qty => transfered_stock_qty)
    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:branch,:transfer_id, :transfered_stock_qty, :part_no, :description, :total_stock_qty, :warehouse_stock_qty, :engineer_stock_qty, :location1, :location2, :location3, :map, :total_stock_value, :status, :latest_modify_date, :remark, :inventory_type_id)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li><%= link_to 'View All Inventory Detail',inventories_path%></li>
    <li>Dashboard</li>
  </ul>
</div>

<div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Inventory
        </div>
<%= form_with(model: inventory, local: true) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="panel-body">
              <div class="row form-group">
             
                    <div class="col-md-3">
                        <label for="text_input" class="label_height">Branch</label>
                             <span style="color:red">*</span>
                          <%= form.text_field :branch, id: :inventory_branch, placeholder: "Branch", class: "form-control"%>
                  </div>  

 <div class="col-md-3">
    <label for="text_input" class="label_height">Part No</label>
         <span style="color:red">*</span>
    <%= form.text_field :part_no, id: :inventory_part_no, placeholder: "Part No", class: "form-control" %>
  </div>

  
 <div class="col-md-3">
    <label for="text_input" class="label_height">Total Stock Qty</label>
         <span style="color:red">*</span>
    <%= form.text_field :total_stock_qty, id: :inventory_total_stock_qty, placeholder: "Total Stock Qty", class: "form-control"  %>
  </div>

 <div class="col-md-3">
    <label for="text_input" class="label_height">WareHouse Stock Qty</label>
         <span style="color:red">*</span>
    <%= form.text_field :warehouse_stock_qty, id: :inventory_warehouse_stock_qty, placeholder: "WareHouse Stock Qty", class: "form-control"  %>
  </div>

  
 <div class="col-md-3">
    <label for="text_input" class="label_height">Engineer Stock Qty </label>
         <span style="color:red">*</span>
    <%= form.text_field :engineer_stock_qty, id: :inventory_engineer_stock_qty, placeholder: "Engineer Stock Qty", class: "form-control"  %>
  </div>

 
 <div class="col-md-3">
    <label for="text_input" class="label_height">Location1</label>
         <span style="color:red">*</span>
    <%= form.text_field :location1, id: :inventory_location1, placeholder: "Location1", class: "form-control"  %>
  </div>

 
 <div class="col-md-3">
    <label for="text_input" class="label_height">Location2</label>
         <span style="color:red">*</span>
    <%= form.text_field :location2, id: :inventory_location2 , placeholder: "Location2", class: "form-control"%>
  </div>

 
 <div class="col-md-3">
    <label for="text_input" class="label_height">Location3</label>
         <span style="color:red">*</span>
    <%= form.text_field :location3, id: :inventory_location3, placeholder: "Location3", class: "form-control" %>
  </div>

  
 <div class="col-md-3">
    <label for="text_input" class="label_height">MAP</label>
         <span style="color:red">*</span>
    <%= form.text_field :map, id: :inventory_map, placeholder: "MAP", class: "form-control" %> 
  </div>

  
 <div class="col-md-3">
    <label for="text_input" class="label_height">Total Stock Value</label>
         <span style="color:red">*</span>
    <%= form.text_field :total_stock_value, id: :inventory_total_stock_value, placeholder: "Total Stock Value", class: "form-control"%>
  </div>

 
 <div class="col-md-3">
    <label for="text_input" class="label_height">Status</label>
         <span style="color:red">*</span>
    <%= form.text_field :status, id: :inventory_status , placeholder: "Status", class: "form-control"%>
  </div>


 <div class="col-md-3">
    <label for="text_input" class="label_height">Latest Modify Date</label>
         <span style="color:red">*</span>
    <%= form.date_field :latest_modify_date,:value => Time.now.strftime('%Y-%m-%d'),class: "form-control datepicker" ,style:"width:440px" %>
  </div>
<br><br>
<br><br>
   <div class="col-md-3">
    <label for="text_input" class="label_height">Select Inventory Type</label>
         <span style="color:red">*</span>
    <%= form.select :inventory_type_id, InventoryType.all.collect{|i| [i.name,i.id]},{prompt:true}, class: "form-control" %>
  </div>

   <div class="col-md-3">
    <label for="text_input" class="label_height">Description</label>
         <span style="color:red">*</span>
    <%= form.text_area :description, id: :inventory_description, placeholder: "Description", class: "form-control"  %>
  </div>



 <div class="col-md-3">
    <label for="text_input" class="label_height">Remark</label>
    <%= form.text_area :remark, id: :inventory_remark, placeholder: "Remark", class: "form-control"  %>
  </div>


         <div class="col-sm-2 col-sm-offset-5 input_success">
                          <%= form.submit "Submit", class: 'btn btn-success btn-md form-control'%>
                     </div>
      </div>
            
       <% end %>
        </div>
      </div>

app/views/inventories/_search_all.html.erb
<%= link_to 'New Inventory', new_inventory_path %>
 <div class="box-content" style="overflow-y: auto;height: 550px;width:100%">
<table class="table table-striped table-bordered responsive">
  <% if @inventories.empty? %>
<h4 align="center">No Record Found </h4>
<% else %>
    <tr>
      <th><b>Branch</b></th>
      <th><b>Part no</b></th>
      <th><b>Description</b></th>
      <th><b>Total stock qty</b></th>
      <th><b>Warehouse stock qty</b></th>
      <th><b>Engineer stock qty</b></th>
      <th><b>Map</b></th>
      <th><b>Total stock value</b></th>
      <th><b>Status</b>/</th>
      <th><b>Latest modify date</b></th>
      <th><b>Inventory type</b></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.branch %></td>
        <td><%= inventory.part_no %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.total_stock_qty %></td>
        <td><%= inventory.warehouse_stock_qty %></td>
        <td><%= inventory.engineer_stock_qty %></td>
        <td><%= inventory.map %></td>
        <td><%= inventory.total_stock_value %></td>
        <td><%= inventory.status %></td>
        <td><%= inventory.latest_modify_date %></td>
        <td><%= inventory.inventory_type.name %></td>
        <td><%= link_to 'Transfer', transfer_inventory_transfer_path(inventory.inventory_type.id, inventory.id),class: "btn btn-danger btn-sm"%></td>
        <td><%= link_to 'Show', inventory,class: "btn btn-warning btn-sm"  %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory),class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger btn-sm" %></td>
      </tr>
      <%end%>
       <%end%>
  </tbody>
</table>

<br>


</div></div></div></div>

app/views/inventories/edit.html.erb
<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<div>
  <ul class="breadcrumb">
    <li>Dashboard</li>
        <li><%= link_to 'Home',dashboard_home_index_path%></li>
            <li><%= link_to 'Inventories',inventories_path%></li>
  </ul>
</div>

 <div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
       <div class="panel panel-primary">
            <div class="panel-heading">Inventory Search
        </div>
 <div class="panel-body">
<p id="notice"></p>

<%= form_for :inventory, method: :get,remote:true,id: 'search' do |f|%>
    <b>Search:</b>
      <br>
      <%= text_field_tag :search,"",placeholder:'Search',class:"form-control",style: "width: 300px"%>
<% end %>

<div id="search_inventory">
  <%= render 'search_all'%>
</div>

<script type='text/javascript'>
$('#search').on('change', function() {
 var search;
 Item = $(this).val();
 $.ajax({
   url: '/inventories/search_inventory',
   type: 'GET',
   dataType: 'script',
   data: {search: Item},
   }).done(function(data) {
     $('#search').html(data);
    
   
 });
});
</script>

app/views/inventories/new.html.erb
<%= render 'form', inventory: @inventory %>
<%= link_to 'Back', inventories_path %>

app/views/inventories/search_inventory.js.erb
$('#search_inventory').html("<%= j render('search_all') %>");

app/views/inventories/show.html.erb
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li>Dashboard</li>
  </ul>
</div>
<div class="col-md-12 section-top-5 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Detail
        </div>
<p id="notice"><%= notice %></p>

<div class="panel-body">
              <div class="row form-group">
                <div class="col-md-4"></div>
                <div class="col-md-4">
<p>
  <strong>Branch:</strong>
  <%= @inventory.branch %>
</p>

<p>
  <strong>Part no:</strong>
  <%= @inventory.part_no %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inventory.description %>
</p>

<p>
  <strong>Total stock qty:</strong>
  <%= @inventory.total_stock_qty %>
</p>

<p>
  <strong>Warehouse stock qty:</strong>
  <%= @inventory.warehouse_stock_qty %>
</p>

<p>
  <strong>Engineer stock qty:</strong>
  <%= @inventory.engineer_stock_qty %>
</p>

<p>
  <strong>Location1:</strong>
  <%= @inventory.location1 %>
</p>

<p>
  <strong>Location2:</strong>
  <%= @inventory.location2 %>
</p>

<p>
  <strong>Location3:</strong>
  <%= @inventory.location3 %>
</p>

<p>
  <strong>Map:</strong>
  <%= @inventory.map %>
</p>

<p>
  <strong>Total stock value:</strong>
  <%= @inventory.total_stock_value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @inventory.status %>
</p>

<p>
  <strong>Latest modify date:</strong>
  <%= @inventory.latest_modify_date %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @inventory.remark %>
</p>

<p>
  <strong>Inventory type:</strong>
  <%= @inventory.inventory_type.name %>
</p>
</div>
<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>
</div>
</div></div></div>

app/views/inventories/view_all.html.erb
<div>
  <ul class="breadcrumb">
    <li>Dashboard</li>
        <li><%= link_to 'Home',dashboard_home_index_path%></li>
            <li><%= link_to 'Inventories',inventories_path%></li>
  </ul>
</div>
<div class="row">
 <div class="col-md-1"></div>
  <div class="box col-md-3">
   <div class="pull-left">
<%= form_tag import_inventories_path,url:{action: 'import',controller: 'inventories'}, multipart: true do %>
    <%= file_field_tag :file%>
  <%= submit_tag "Import",class: "btn btn-primary" %>
<% end %>
  <h3><b>Download/Upload:</b></h3>
  <b><%= link_to "Export CSV", inventories_path(format: "csv") %></b> |
  <b><%= link_to "Excel", inventories_path(format: "xls") %></b>
</div>
</div>
</div>
 <div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
       <div class="panel panel-primary">
            <div class="panel-heading">Inventory Details
        </div>
 <div class="panel-body">
<p id="notice"></p>

<%= link_to 'New Inventory', new_inventory_path %>
 <div class="box-content" style="overflow-y: auto;height: 550px;width:100%">
<table class="table table-striped table-bordered responsive">

    <tr>
      <th><b>Branch</b></th>
      <th><b>Part no</b></th>
      <th><b>Description</b></th>
      <th><b>Total stock qty</b></th>
      <th><b>Warehouse stock qty</b></th>
      <th><b>Engineer stock qty</b></th>
      <th><b>Map</b></th>
      <th><b>Total stock value</b></th>
      <th><b>Status</b>/</th>
      <th><b>Latest modify date</b></th>
      <th><b>Inventory type</b></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%total_amt = 0%>
   <%total_stock_qty_amt = 0%>
    <%total_warehouse_qty = 0%>
     <%total_map_amt = 0%>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.branch %></td>
        <td><%= inventory.part_no %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.total_stock_qty %></td>
        <td><%= inventory.warehouse_stock_qty %></td>
        <td><%= inventory.engineer_stock_qty %></td>
        <td><%= inventory.map %></td>
        <td><%= inventory.total_stock_value %></td>
        <td><%= inventory.status %></td>
        <td><%= inventory.latest_modify_date %></td>
        <td><%= inventory.inventory_type.name %></td>
        <td><%= link_to 'Transfer', transfer_inventory_transfer_path(inventory.inventory_type.id, inventory.id),class: "btn btn-danger btn-sm"%></td>
        <td><%= link_to 'Show', inventory,class: "btn btn-warning btn-sm"  %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory),class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger btn-sm" %></td>
      </tr>
     <% total_amt += inventory.total_stock_value.to_i%>
      <%total_stock_qty_amt += inventory.total_stock_qty.to_i%>
      <% total_warehouse_qty += inventory.warehouse_stock_qty.to_i%>
      <% total_map_amt += inventory.map.to_i%>
      <%end%>
      <div class= "container">
        <div class = "pull-right">
       <b>Total Stock Qty : <%=total_stock_qty_amt%></b><br>
      <b>Total Stock Value : <%=total_amt%></b><br>
      <b>Total WareHouse Stock Qty : <%=total_warehouse_qty%></b><br>
      <b>Total MAP : <%=total_map_amt%></b><br>
      </div>
      </div>
  </tbody>
</table>

<br>


</div></div></div></div>