config/routes.rb
Rails.application.routes.draw do
  
  resources :customer_details do
    collection do 
      get :existing_customer, :search_customer, :status, :update_search, :search_customer_status, :customer_status
      get :existing_customer, :search_customer, :work_done, :pending_status, :good_delivered, :show_work_done
      get :show_pending_status, :show_good_delivered, :report, :show_transactions_list
      post :transactions_list
    end
    member do
       get :customer_receipt, :show_engineer_copy, :inventory_item, :inventory, :without_adding_items, :invoice, :edit_status
      patch :update_status
    end
     resources :inventory_items
  end

   resources :inventory_items do
    collection do 
      get :select_inventory,:select
    end
    member do
      get :add_product_existing_customer, :show_invoice
    end
  end


  resources :engineer_details 

  resources :inventories do
    collection do
      post :import
      get  :load_item_data
      get :search_inventory
      get :view_all
    end
  end

  resources :inventory_types

  root 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :employees
  resources :employee_types
  resources :general_settings
 
  resources :home do
  	collection do
  		get :dashboard
  	end
  end

  resources :inventory_transfers do
    collection do
      get :select
      get :assign_all
      get :remove_all
      get :inventory_transfer
    end
    member do
      get :transfer
    end
  end

  resources :reports do 
    collection do
    get :select, :report, :transfer
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :employee_type
  belongs_to :user, optional:true
  has_many :customer_details
  after_save :create_user_account
  validates :employee_number, presence: true
  validates :contact, presence: true
  validates :email, presence: true, format: \
  { with: /\A[a-zA-Z0-9._-]+@([a-zA-Z0-9]+\.)+[a-zA-Z]{2,4}+\z/ }

   # this method is used to calculate the employee number
  # if first employee then append 1 to today date else
  # append last id to today date
  def emp_no
    date = Date.today.strftime('%Y%m%d')
    self.employee_number = date.to_s + '1' if Employee.first.nil?
    self.employee_number = date.to_s + \
                           Employee.last.id.next.to_s unless Employee.first.nil?
  end

  private

  # This action create the user for employee login.
  def create_user_account
    user = User.new do |u|
      u.email = email
      u.employee_id = id 
      u.password = employee_number
      u.role = 'Employee'
      u.general_setting_id = if User.current
                               User.current.general_setting_id
                             else
                               1
                             end
    end
    user.save
  end
end

app/models/employee_type.rb
class EmployeeType < ApplicationRecord
	validates :name, presence:true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee.emp_no
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_number,:first_name, :middle_name, :last_name, :contact, :email, :address, :employee_type_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
     <li><%= link_to 'View All Employee Detail',employees_path%></li>
    <li>Dashboard</li>
  </ul>
</div>
<div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Type
        </div>
        <%= form_with(model: employee, local: true) do |form| %>
          <% if employee.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

              <ul>
              <% employee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="panel-body">
              <div class="row form-group">
              <div class="col-md-4">
                        <label for="text_input" class="label_height">Employee Number</label>
                             <span style="color:red">*</span>
              <%=form.text_field :employee_number,readonly: true,:value=> @employee.employee_number, class: "form-control"%>
              </div>
                    <div class="col-md-4">
                        <label for="text_input" class="label_height">First Name</label>
                             <span style="color:red">*</span>
                            <%=  form.text_field :first_name, id: :employee_first_name, placeholder: "Employee First Name", class: "form-control"%>
                    </div>

                     <div class="col-md-4">
                        <label for="text_input" class="label_height">Middle Name</label>
                             <span style="color:red">*</span>
                            <%=  form.text_field :middle_name, id: :employee_middle_name, placeholder: "Employee Middle Name", class: "form-control"%>
                    </div>

                     <div class="col-md-4">
                        <label for="text_input" class="label_height">Last Name</label>
                             <span style="color:red">*</span>
                            <%=   form.text_field :last_name, id: :employee_last_name, placeholder: "Employee Last Name", class: "form-control"%>
                    </div>

                     <div class="col-md-4">
                        <label for="text_input" class="label_height">Contact</label>
                             <span style="color:red">*</span>
                            <%=   form.text_field :contact, id: :contact, placeholder: "Contact", class: "form-control"%>
                    </div>

                     <div class="col-md-4">
                        <label for="text_input" class="label_height">Email</label>
                             <span style="color:red">*</span>
                            <%=  form.text_field :email, id: :email, placeholder: "Email", class: "form-control"%>
                    </div>

                     <div class="col-md-4">
                        <label for="text_input" class="label_height">Address</label>
                             <span style="color:red">*</span>
                            <%=  form.text_field :address, id: :address, placeholder: "Address", class: "form-control"%>
                    </div>

                     <div class="col-md-4">
                        <label for="text_input" class="label_height">Employee Type</label>
                             <span style="color:red">*</span>
                            <%=  form.select :employee_type_id,EmployeeType.all.collect{|e| [e.name, e.id]},{prompt:true}, placeholder: "Employee Type", class: "form-control"%>
                    </div>

                
                </div>
                     <div class="col-sm-2 col-sm-offset-5 input_success">
                          <%= form.submit "Submit", class: 'btn btn-success btn-md form-control'%>
                     </div>
              </div>
              </div>
       <% end %>

app/views/employees/edit.html.erb
<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li>Dashboard</li>
  </ul>
</div>
 <div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
       <div class="panel panel-primary">
            <div class="panel-heading">Employee Details
        </div>
 <div class="panel-body">
<p id="notice"><%= notice %></p>
<%= link_to 'New Employee', new_employee_path %>
 <div class="box-content" style="overflow-y: auto;height: 550px;width:100%">
<table class="table table-striped table-bordered responsive">
  <thead>
    <tr>
     <th><b>Employee Number</b></th>
      <th><b>First name</b></th>
      <th><b>Middle name</b></th>
      <th><b>Last name</b></th>
      <th><b>Contact<b></th>
      <th><b>Email<b></th>
      <th><b>Address</b></th>
      <th><b>Employee type</b></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
      <td><%= employee.employee_number%></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.middle_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.contact %></td>
        <td><%= employee.email %></td>
        <td><%= employee.address %></td>
        <td><%= employee.employee_type.name %></td>
        <td><%= link_to 'Show', employee,class: "btn btn-warning btn-sm"  %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee),class: "btn btn-success btn-sm"  %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div></div></div>

app/views/employees/new.html.erb
<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li>Dashboard</li>
  </ul>
</div>
<div class="col-md-12 section-top-5 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Detail
        </div>
<p id="notice"><%= notice %></p>

<div class="panel-body">
              <div class="row form-group">
                <div class="col-md-4"></div>
                <div class="col-md-4">
  <strong>Employee Number:</strong>
  <%= @employee.employee_number %><br>
             
  <strong>First name:</strong>
  <%= @employee.first_name %><br>

  <strong>Middle name:</strong>
  <%= @employee.middle_name %><br>

  <strong>Last name:</strong>
  <%= @employee.last_name %><br>

  <strong>Contact:</strong>
  <%= @employee.contact %><br>

  <strong>Email:</strong>
  <%= @employee.email %><br>

               
  <strong>Address:</strong>
  <%= @employee.address %><br>

                  
  <strong>Employee type:</strong>
  <%= @employee.employee_type.name %><br>
</div>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>
</div>
</div></div></div>