config/routes.rb
Rails.application.routes.draw do
  
  resources :customer_details do
    collection do 
      get :existing_customer, :search_customer, :status, :update_search, :search_customer_status, :customer_status
      get :existing_customer, :search_customer, :work_done, :pending_status, :good_delivered, :show_work_done
      get :show_pending_status, :show_good_delivered, :report, :show_transactions_list
      post :transactions_list
    end
    member do
       get :customer_receipt, :show_engineer_copy, :inventory_item, :inventory, :without_adding_items, :invoice, :edit_status
      patch :update_status
    end
     resources :inventory_items
  end

   resources :inventory_items do
    collection do 
      get :select_inventory,:select
    end
    member do
      get :add_product_existing_customer, :show_invoice
    end
  end


  resources :engineer_details 

  resources :inventories do
    collection do
      post :import
      get  :load_item_data
      get :search_inventory
      get :view_all
    end
  end

  resources :inventory_types

  root 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :employees
  resources :employee_types
  resources :general_settings
 
  resources :home do
  	collection do
  		get :dashboard
  	end
  end

  resources :inventory_transfers do
    collection do
      get :select
      get :assign_all
      get :remove_all
      get :inventory_transfer
    end
    member do
      get :transfer
    end
  end

  resources :reports do 
    collection do
    get :select, :report, :transfer
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/employee_types_controller.rb
class EmployeeTypesController < ApplicationController
  before_action :set_employee_type, only: [:show, :edit, :update, :destroy]

  # GET /employee_types
  # GET /employee_types.json
  def index
    @employee_types = EmployeeType.all
  end

  # GET /employee_types/1
  # GET /employee_types/1.json
  def show
  end

  # GET /employee_types/new
  def new
    @employee_type = EmployeeType.new
  end

  # GET /employee_types/1/edit
  def edit
  end

  # POST /employee_types
  # POST /employee_types.json
  def create
    @employee_type = EmployeeType.new(employee_type_params)

    respond_to do |format|
      if @employee_type.save
        format.html { redirect_to employee_types_path, notice: 'Employee type was successfully created.' }
        format.json { render :show, status: :created, location: @employee_type }
      else
        format.html { render :new }
        format.json { render json: @employee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_types/1
  # PATCH/PUT /employee_types/1.json
  def update
    respond_to do |format|
      if @employee_type.update(employee_type_params)
        format.html { redirect_to @employee_type, notice: 'Employee type was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_type }
      else
        format.html { render :edit }
        format.json { render json: @employee_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_types/1
  # DELETE /employee_types/1.json
  def destroy
    @employee_type.destroy
    respond_to do |format|
      format.html { redirect_to employee_types_url, notice: 'Employee type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_type
      @employee_type = EmployeeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_type_params
      params.require(:employee_type).permit(:name)
    end
end

app/helpers/employee_types_helper.rb
module EmployeeTypesHelper
end

app/views/employee_types/_form.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li><%= link_to 'View All Employee Type',employee_types_path%></li>
    <li>Dashboard</li>
  </ul>
</div>

<div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Type
        </div>
        <%= form_with(model: employee_type, local: true) do |form| %>
          <% if employee_type.errors.any? %>
             <div id="error_explanation">
                <h2><%= pluralize(employee_type.errors.count, "error") %> prohibited this employee_type from being saved:</h2> <ul>
                      <% employee_type.errors.full_messages.each do |message| %>
                       <li><%= message %></li>
                  <% end %>
                    </ul>
              </div>
          <% end %>
          <div class="panel-body">
              <div class="row form-group">
                <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <label for="text_input" class="label_height">Add Employee Type</label>
                             <span style="color:red">*</span>
                            <%= form.text_field :name, id: :employee_type_name, placeholder: "Employee Type", class: "form-control"%>
                    </div>
                </div>
                     <div class="col-sm-2 col-sm-offset-5 input_success">
                          <%= form.submit "Submit", class: 'btn btn-success btn-md form-control'%>
                     </div>
              </div>
          </div>
       <% end %>
</div>

app/views/employee_types/edit.html.erb
<%= render 'form', employee_type: @employee_type %>

<%= link_to 'Show', @employee_type %> |
<%= link_to 'Back', employee_types_path %>

app/views/employee_types/index.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li><%= link_to 'Employee Types',employee_types_path%></li>
    <li>Dashboard</li>
  </ul>
</div>

 <div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
       <div class="panel panel-primary">
            <div class="panel-heading">Employees Type Details
        </div>
 <div class="panel-body">
 <p id="notice"><%= notice %></p>
<%= link_to "Add New Employee Type",new_employee_type_path%>
 <div class="box-content" style="overflow-y: auto;height: 550px;width:100%">
<table class="table table-striped table-bordered responsive">
                                <thead>
                                    <tr>
                                        <th><b>Name</b></th>
                                        <th colspan="5"></th>
                                    </tr>
                                 </thead>

                                  <tbody>
                                    <% @employee_types.each do |employee_type| %>
                                        <tr>
                                          <td><%= employee_type.name %></td>
                                          <td><%= link_to 'Show', employee_type, class: "btn btn-success btn-sm" %></td>
                                          <td><%= link_to 'Edit', edit_employee_type_path(employee_type), class: "btn btn-danger btn-sm" %></td>
                                          <td><%= link_to 'Destroy', employee_type, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-warning btn-sm" %></td>
                                        </tr>
                                    <% end %>
                                 </tbody>
</table>
</div>
</div>
</div>

app/views/employee_types/new.html.erb
<%= render 'form', employee_type: @employee_type %>

<%= link_to 'Back', employee_types_path %>

app/views/employee_types/show.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li>Dashboard</li>
  </ul>
</div>
<p id="notice"><%= notice %></p>

<div class="col-md-12 section-top-5 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Detail
        </div>
<p id="notice"><%= notice %></p>

<div class="panel-body">
              <div class="row form-group">
                <div class="col-md-4"></div>
                <div class="col-md-4">
             
  <strong>Name:</strong>
  <%= @employee_type.name %>
</div>
<%= link_to 'Edit', edit_employee_type_path(@employee_type) %> |
<%= link_to 'Back', employee_types_path %>
</div>
</div></div></div>