config/routes.rb
Rails.application.routes.draw do
  
  resources :customer_details do
    collection do 
      get :existing_customer, :search_customer, :status, :update_search, :search_customer_status, :customer_status
      get :existing_customer, :search_customer, :work_done, :pending_status, :good_delivered, :show_work_done
      get :show_pending_status, :show_good_delivered, :report, :show_transactions_list
      post :transactions_list
    end
    member do
       get :customer_receipt, :show_engineer_copy, :inventory_item, :inventory, :without_adding_items, :invoice, :edit_status
      patch :update_status
    end
     resources :inventory_items
  end

   resources :inventory_items do
    collection do 
      get :select_inventory,:select
    end
    member do
      get :add_product_existing_customer, :show_invoice
    end
  end


  resources :engineer_details 

  resources :inventories do
    collection do
      post :import
      get  :load_item_data
      get :search_inventory
      get :view_all
    end
  end

  resources :inventory_types

  root 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :employees
  resources :employee_types
  resources :general_settings
 
  resources :home do
  	collection do
  		get :dashboard
  	end
  end

  resources :inventory_transfers do
    collection do
      get :select
      get :assign_all
      get :remove_all
      get :inventory_transfer
    end
    member do
      get :transfer
    end
  end

  resources :reports do 
    collection do
    get :select, :report, :transfer
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/inventory_types_controller.rb
class InventoryTypesController < ApplicationController
  before_action :set_inventory_type, only: [:show, :edit, :update, :destroy]

  # GET /inventory_types
  # GET /inventory_types.json
  def index
    @inventory_types = InventoryType.all
  end

  # GET /inventory_types/1
  # GET /inventory_types/1.json
  def show
  end

  # GET /inventory_types/new
  def new
    @inventory_type = InventoryType.new
  end

  # GET /inventory_types/1/edit
  def edit
  end

  # POST /inventory_types
  # POST /inventory_types.json
  def create
    @inventory_type = InventoryType.new(inventory_type_params)

    respond_to do |format|
      if @inventory_type.save
        format.html { redirect_to @inventory_type, notice: 'Inventory type was successfully created.' }
        format.json { render :show, status: :created, location: @inventory_type }
      else
        format.html { render :new }
        format.json { render json: @inventory_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_types/1
  # PATCH/PUT /inventory_types/1.json
  def update
    respond_to do |format|
      if @inventory_type.update(inventory_type_params)
        format.html { redirect_to @inventory_type, notice: 'Inventory type was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_type }
      else
        format.html { render :edit }
        format.json { render json: @inventory_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_types/1
  # DELETE /inventory_types/1.json
  def destroy
    @inventory_type.destroy
    respond_to do |format|
      format.html { redirect_to inventory_types_url, notice: 'Inventory type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_type
      @inventory_type = InventoryType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_type_params
      params.require(:inventory_type).permit(:name)
    end
end

app/helpers/inventory_types_helper.rb
module InventoryTypesHelper
end

app/views/inventory_types/_form.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li><%= link_to 'View All Inventory Type',inventory_types_path%></li>
    <li>Dashboard</li>
  </ul>
</div>

<div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Type
        </div>
<%= form_with(model: inventory_type, local: true) do |form| %>
  <% if inventory_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory_type.errors.count, "error") %> prohibited this inventory_type from being saved:</h2>

      <ul>
      <% inventory_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

   <div class="panel-body">
              <div class="row form-group">
                <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <label for="text_input" class="label_height">Add Inventory Type</label>
                             <span style="color:red">*</span>
                            <%= form.text_field :name, id: :inventory_type_name, placeholder: "Inventory Type", class: "form-control"%>
                    </div>
                </div>
                     <div class="col-sm-2 col-sm-offset-5 input_success">
                          <%= form.submit "Submit", class: 'btn btn-success btn-md form-control'%>
                     </div>
              </div>
          </div>
       <% end %>
</div>

app/views/inventory_types/edit.html.erb
<%= render 'form', inventory_type: @inventory_type %>
<%= link_to 'Show', @inventory_type %> |
<%= link_to 'Back', inventory_types_path %>

app/views/inventory_types/index.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li><%= link_to 'Inventory Types',inventory_types_path%></li>
    <li>Dashboard</li>
  </ul>
</div>

 <div class="col-md-12 section-top-15 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
       <div class="panel panel-primary">
            <div class="panel-heading">Inventory Type Details
        </div>
 <div class="panel-body">
 <p id="notice"><%= notice %></p>
<%= link_to "Add New Inventory Type",new_inventory_type_path%>
 <div class="box-content" style="overflow-y: auto;height: 550px;width:100%">
<table class="table table-striped table-bordered responsive">
    <tr>
    <th><b>InventoryType Id</b></th>
      <th><b>Name</b></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_types.each_with_index do |inventory_type,i| %>
      <tr>
        <td><%= i + 1%></td>
        <td><%= inventory_type.name %></td>
        <td><%= link_to 'Show', inventory_type, class: "btn btn-success btn-sm"%></td>
        <td><%= link_to 'Edit', edit_inventory_type_path(inventory_type), class: "btn btn-danger btn-sm" %></td>
        <td><%= link_to 'Destroy', inventory_type, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-warning btn-sm" %></td>
      </tr>
    <% end %>
                                 </tbody>
</table>
</div>
</div>
</div>

app/views/inventory_types/new.html.erb
<%= render 'form', inventory_type: @inventory_type %>
<%= link_to 'Back', inventory_types_path %>

app/views/inventory_types/show.html.erb
<div>
  <ul class="breadcrumb">
    <li><%= link_to 'Home',dashboard_home_index_path%></li>
    <li>Dashboard</li>
  </ul>
</div>


<div class="col-md-12 section-top-5 wow fadeInDown" data-wow-duration="1s"
                             data-wow-delay="0.2s">
        <div class="panel panel-primary">
            <div class="panel-heading">Employee Detail
        </div>
<p id="notice"><%= notice %></p>

<div class="panel-body">
              <div class="row form-group">
                <div class="col-md-4"></div>
                <div class="col-md-4">
             
  <strong>Name:</strong>
 
  <%= @inventory_type.name %>
</div>
<%= link_to 'Edit', edit_inventory_type_path(@inventory_type) %> |
<%= link_to 'Back', inventory_types_path %>
</div>
</div></div></div>